version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - canvural
  assignees:
  - canvural
  versioning-strategy: increase
  ignore:
  - dependency-name: orchestra/testbench
    versions:
    - ">= 6.a, < 7"
  - dependency-name: orchestra/testbench
    versions:
    - 5.18.0
